### ISSUE TITLE
where do you use "next_state" in def train(self):

### ISSUE THREAD

**Issue by yoshina621** [Huixxi/TensorFlow2.0-for-Deep-Reinforcement-Learning#1]
you get next_state from self.get_n_step_info(self.n_step_buffer, self.gamma), but the next_state is not used.
may be self.store_transition(p, obs, action, reward, next_obs, done) should be self.store_transition(p, obs, action, reward, next_state, done).

**Comment by Huixxi** [comment]
Oh, sorry, I just see this issue. I think maybe you're right, thanks a lot dude, I've corrected it to 
`reward, next_obs, done = self.get_n_step_info(self.n_step_buffer, self.gamma)`. You can check it now.
